#!/usr/bin/env python3
"""Materialize one FUTURE.md sprint section into docs/plans/SPRINT.md."""

from __future__ import annotations

import argparse
import re
from pathlib import Path


SPRINT_RE = re.compile(r"^### Sprint (?P<number>\d+)[：:](?P<title>.+)$", re.MULTILINE)


def _repo_root() -> Path:
    return Path(__file__).resolve().parents[4]


def _read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8")


def _find_sprints(future_text: str) -> list[re.Match[str]]:
    return list(SPRINT_RE.finditer(future_text))


def extract_sprint(future_text: str, sprint_number: int) -> tuple[str, str]:
    matches = _find_sprints(future_text)
    for index, match in enumerate(matches):
        if int(match.group("number")) != sprint_number:
            continue
        start = match.start()
        end = matches[index + 1].start() if index + 1 < len(matches) else len(future_text)
        title = match.group("title").strip()
        return title, future_text[start:end].strip()
    available = ", ".join(m.group("number") for m in matches) or "none"
    raise SystemExit(f"Sprint {sprint_number} not found in FUTURE.md. Available: {available}")


def render_sprint(sprint_number: int, title: str, body: str) -> str:
    return f"""# Deep Thought - Current Sprint

> Source: `docs/plans/FUTURE.md` / Sprint {sprint_number}: {title}
> Generated by `.agents/skills/sprint/scripts/materialize_sprint.py`.

## Execution Checklist

- [ ] Read `AGENTS.md`, `docs/plans/FUTURE.md`, this file, and `docs/plans/pitfalls.md`.
- [ ] Confirm the sprint scope and affected target modules.
- [ ] Implement only the unfinished items in this sprint.
- [ ] Update this checklist as items complete.
- [ ] Run the acceptance commands listed in the sprint contract.
- [ ] Update `docs/project_structure.md` if file layout or ownership changed.
- [ ] Append completed sprint notes to `docs/plans/HISTORY.md`.
- [ ] Append newly discovered recurring hazards to `docs/plans/pitfalls.md`.

## Sprint Contract

{body}
"""


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--sprint", type=int, required=True, help="Sprint number from docs/plans/FUTURE.md")
    parser.add_argument("--future", type=Path, default=None, help="Path to FUTURE.md")
    parser.add_argument("--output", type=Path, default=None, help="Path to SPRINT.md")
    args = parser.parse_args()

    root = _repo_root()
    future_path = args.future or root / "docs" / "plans" / "FUTURE.md"
    output_path = args.output or root / "docs" / "plans" / "SPRINT.md"

    title, body = extract_sprint(_read_text(future_path), args.sprint)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(render_sprint(args.sprint, title, body), encoding="utf-8")
    print(f"Wrote {output_path} from Sprint {args.sprint}: {title}")


if __name__ == "__main__":
    main()
